services:
  app:
    build: .
    container_name: roans-banking-dashboard
    ports:
      - "${APP_PORT:-8200}:8200"
    volumes:
      - ./config/:/app/config/
      - ./.env:/app/.env:ro
      - data:/app/data
    restart: unless-stopped

volumes:
  data:
