services:
  app:
    build:
      context: ..
      dockerfile: Docker/Dockerfile
    container_name: roans-banking-dashboard
    ports:
      - "8200:8200"
    volumes:
      - ./config/:/app/config/
      - ./.env:/app/.env:ro
      - data:/app/data
    restart: unless-stopped

volumes:
  data:
